# Project keys
sonar.python.coverage.reportPaths=coverage.xml
sonar.organization=defk0rn
sonar.projectKey=DefK0rn_python-project-83

# Environment 
sonar.sources=page_analyzer
sonar.tests=tests
sonar.coverage.exclusions=tests/**